# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32)),
                ('user_pass', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_phone', models.CharField(max_length=11)),
            ],
        ),
    ]
