# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=255)),
                ('site_url', models.CharField(max_length=255)),
            ],
        ),
    ]
