# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('sign_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.IntegerField(max_length=11)),
                ('site_name', models.CharField(max_length=255)),
                ('site_pass', models.CharField(max_length=255)),
                ('site_time', models.TimeField()),
                ('user_id', models.IntegerField(max_length=11)),
            ],
        ),
    ]
