# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_id', models.IntegerField(max_length=11)),
                ('sign_status', models.CharField(max_length=32)),
                ('detail_time', models.DateTimeField()),
                ('detail_points', models.IntegerField(max_length=11)),
            ],
        ),
    ]
